base_model: dvdmrs09/peft-gemma-2b-v9
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
load_in_8bit: false
load_in_4bit: true
strict: false

# huggingface repo
datasets:
  - path: ./python-oasst/cleaned-dataset.jsonl
    type: oasst
val_set_size: 0.20
output_dir: ./out8m

adapter: qlora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
gptq: false
sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project: gemma-2b-it
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:


gradient_accumulation_steps: 3
micro_batch_size: 4
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: true
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.1
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 256
saves_per_epoch: 1
debug:
deepspeed: deepspeed_configs/zero1.json

weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
